web:
  ## Sets the title at the top of the status page
  title: MyApp Status

## This is the directory, relative to the config file, where all data
## will be stored. This includes every historical check ever run.
dbDirectory: db

## Map consisting of services to display on your statuspage. Each service
## can have multiple checks. Each check runs in its own docker container, so
## you have the luxury of picking a docker image that already has the tools
## you need. If no image is given, it defaults to `byrnedo/alpine-curl` - which
## is an image built from alpine linux but with curl.
##
## All check commands are simply run using the default shell in the image (/bin/sh).
services:
  API:
    checks:
      - name: API Status
        interval: 60s
        cmd: 'curl -fsSL https://app.myapp.com/api/v0/status'
    notifications:
      # Have you tried turning it off & on again?
      on_failure:
        - type: webhook
          options:
            method: delete
            url: https://api.heroku.com/apps/MY_HEROKU_APP/dynos
            headers:
              Authorization: 'Bearer heroku-token'
              Accept: 'application/vnd.heroku+json; version=3'
  Web:
    - name: Web delivers homepage
      interval: 60s
      cmd: 'curl -fsSL -o /dev/null https://app.myapp.ca/'
    - name: Web delivers login
      interval: 60s
      cmd: 'curl -fsSL -o /dev/null https://app.myapp.ca/login'
  Redis:
    - name: Responds to pings
      interval: 60s
      image: redis:5
      cmd: '! redis-cli -h redis.ca -n 0 -a pass ping | grep ERR'
  Mongo:
    - name: Users exist
      interval: 60s
      image: mongo:4.2
      cmd: 'test "`mongo "mongodb://user:pwd@mongo.com/myapp" --eval "db.users.estimatedDocumentCount()" | tail -n 1`" != "0"'

notifications:
  ## Array of notifications to emit when checks fail
  ## Currently, only a webhook is supported. All options are passed directly to `request` - but
  ## string bodies get interpolated with information about the check that triggered the notification.
  on_failure:
    - type: webhook
      options:
        method: post
        url: https://hooks.slack.com/services/MY_CUSTOM_WEBHOOK
        headers:
          'Content-Type': 'application/json'
        body: '{"text":"Service \"{{service}}\" is down (check \"{{check.name}}\" failed)."}'
  ## Array of notifications to emit when checks complete successfully occur
  ## Depending on your interval settings, this might be a hell of a lot.
  on_success:
    - type: webhook
      options:
        method: post
        url: https://hooks.slack.com/services/MY_CUSTOM_WEBHOOK
        headers:
          'Content-Type': 'application/json'
        body: '{"text":"Service \"{{service}}\" is up (check \"{{check.name}}\" completed)."}'
