name: CI
on:
  push: {}
  pull_request:
    branches: [ master ]
env:
  GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    # - name: SSH Session for Debugging Failure
    #   uses: mxschmitt/action-tmate@v1
    - name: Install
      run: npm ci && NODE_ENV=production go generate
    - name: Test
      run: |
        go test ./... -race
        find . -name '*.db' -type f | xargs rm
    - name: Build
      run: docker build -t ghcr.io/karimsa/patrol:unstable .
    - name: Login to registry
      run: docker login --username=karimsa --password=$GH_REGISTRY_TOKEN ghcr.io
    - name: Release unstable
      run: docker push ghcr.io/karimsa/patrol:unstable
    - name: Release stable
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        docker tag ghcr.io/karimsa/patrol:unstable ghcr.io/karimsa/patrol:latest
        docker push ghcr.io/karimsa/patrol:latest
