name: CI
on:
  push: {}
  pull_request:
    branches: [ master ]
env:
  GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 14.x
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    # - name: SSH Session for Debugging Failure
    #   uses: mxschmitt/action-tmate@v1
    - name: Install
      run: npm ci
    - name: Build css
      run: npm run build
    - name: Test
      run: |
        go test ./... -race
        find . -name '*.db' -type f | xargs rm
    - name: Build x86 image
      run: docker build -t ghcr.io/karimsa/patrol:unstable .
    - name: Build arm64v8 image
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker build --platform linux/arm64 -t ghcr.io/karimsa/patrol:unstable-arm64v8 -f Dockerfile.arm64v8 .
    - name: Login to registry
      run: docker login --username=karimsa --password=$GH_REGISTRY_TOKEN ghcr.io
    - name: Release unstable
      run: |
        docker push ghcr.io/karimsa/patrol:unstable
        docker push ghcr.io/karimsa/patrol:unstable-arm64v8
    - name: Release stable
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        docker tag ghcr.io/karimsa/patrol:unstable ghcr.io/karimsa/patrol:latest
        docker push ghcr.io/karimsa/patrol:latest

        docker tag ghcr.io/karimsa/patrol:unstable-arm64v8 ghcr.io/karimsa/patrol:latest-arm64v8
        docker push ghcr.io/karimsa/patrol:latest-arm64v8
