name: CI
on:
  push: {}
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: SSH Session for Debugging Failure
      uses: mxschmitt/action-tmate@v1
    - name: Build
      run: docker build -t patrol .
